apiVersion: v1
kind: Service
metadata:
  name: board-svc
spec:
  ports:
    - name: "8090"
      port: 8092
      targetPort: 8090
  selector:
    app: board-api
  clusterIP: 10.107.154.31
  type: LoadBalancer