apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonar
  name: sonar
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 30002
      name: sonarport
  selector:
    app: sonarqube
