apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
        - name: gateway-api
          image: sktellecom/ms-test:gateway-api
          ports:
            - containerPort: 8090
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "1Gi"
      imagePullSecrets:
        - name: ms-secret