kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: board-pvc
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: board-file
