apiVersion: v1
kind: PersistentVolume
metadata:
  name: board-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: board-file
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /board
    server: 192.168.245.130